# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailer::wakamail.form_name

# Model Form Field configuration
form: $/waka/mailer/models/wakamail/fields.yaml

# Model Class name
modelClass: Waka\Mailer\Models\WakaMail

# Default redirect location
defaultRedirect: waka/mailer/wakamails/index/wakamails

# Create page
create:
    title: waka.mailer::wakamail.create
    redirect: waka/mailer/wakamails/update/:id
    redirectClose: waka/mailer/wakamails/index/wakamails
    form: $/waka/mailer/models/wakamail/fields_create.yaml

# Update page
update:
    title: waka.mailer::wakamail.update
    redirect: waka/mailer/wakamails/update/:id
    redirectClose: waka/mailer/wakamails/index/wakamails

# Preview page
preview:
    title: waka.mailer::wakamail.preview_name
