# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: WakaMail

# Model Form Field configuration
form: $/waka/mailer/models/wakamail/fields.yaml

# Model Class name
modelClass: Waka\Mailer\Models\WakaMail

# Default redirect location
defaultRedirect: waka/mailer/wakamails

# Create page
create:
    title: Nouveau modèle email
    redirect: waka/mailer/wakamails/update/:id
    redirectClose: waka/mailer/wakamails

# Update page
update:
    title: Editer modèle email
    redirect: waka/mailer/wakamails
    redirectClose: waka/mailer/wakamails

# Preview page
preview:
    title: Preview WakaMail
