# ===================================
#  Relation Behavior Config
# ===================================




blocs:
    label: waka.mailer::lang.bloc.code
    manage:
        form: $/waka/mailer/models/bloc/fields.yaml
    view:
        list: $/waka/mailer/models/bloc/columns_for_wakamail.yaml
        toolbarButtons: delete
        defaultSort:
            column: sort_order
            direction: asc

scope_functions:
    label: waka.utils::lang.scope_functions.name
    manage:
        toolbarButtons: add|remove
        list: $/waka/utils/models/scopefunction/columns.yaml
        form: $/waka/utils/models/scopefunction/pivot.yaml
    view:
        list: $/waka/utils/models/scopefunction/columns.yaml
    pivot:
        form:
            fields:
                pivot[options]:
                    label: Options
        



