label:
    name: Label/Titre
    description: Ajouter un titre ou un label
    titleFrom: name
    icon: icon-file-text-o
    fields:
        code:
            label: code
            span: left
        is_asked:
            label: Demander
            type: checkbox
            default: true
            span: right
        content:
            span: full
            label: description
            size: small
textarea:
    name: Ajouter un texte
    description: Ajouter un texte su plusieurs lignes
    icon: icon-file-text-o
    fields:
        code:
            label: code
            span: left
        is_asked:
            label: Demander
            type: checkbox
            default: true
            span: right
        content:
            label: le texte
            type: textarea
            span: full
            size: tiny
markdown:
    name: Ajouter un texte markdown
    description: Ajouter un texte su plusieurs lignes en markdown
    icon: icon-file-text-o
    fields:
        code:
            label: code
            span: left
        is_asked:
            label: Demander
            type: checkbox
            default: true
            span: right
        content:
            label: le texte
            type: markdown
            span: full
            size: tiny
richeditor:
    name: Ajouter un texte html
    description: Ajouter un texte su plusieurs lignes en markdown
    icon: icon-file-text-o
    fields:
        code:
            label: code
            span: left
        is_asked:
            label: Demander
            type: checkbox
            default: true
            span: right
        content:
            label: le texte
            type: richeditor
            span: full
            size: small
            toolbarButtons: bold|italic