# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder wakamails

# Attribute name
nameFrom: name

# Model Class name
modelClass: Waka\Mailer\Models\WakaMail

# Toolbar widget configuration
#toolbar:
    # Partial for toolbar buttons
    # buttons: reorder_toolbar