# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailer::template.form_name

# Model Form Field configuration
form: $/waka/mailer/models/template/fields.yaml

# Model Class name
modelClass: Waka\Mailer\Models\Template

# Default redirect location
defaultRedirect: waka/mailer/templates

# Create page
create:
    title: Create Template
    redirect: waka/mailer/templates/update/:id
    redirectClose: waka/mailer/templates

# Update page
update:
    title: Edit Template
    redirect: waka/mailer/templates
    redirectClose: waka/mailer/templates

# Preview page
preview:
    title: waka.mailer::template.preview_name
