# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailer::bloc.form_name

# Model Form Field configuration
form: $/waka/mailer/models/bloc/fields.yaml

# Model Class name
modelClass: Waka\Mailer\Models\Bloc

# Default redirect location
defaultRedirect: waka/mailer/wakamails/index/blocs

# Create page
create:
    title: waka.mailer::bloc.create
    redirect: waka/mailer/blocs/update/:id
    redirectClose: waka/mailer/wakamails/index/blocs
    form: $/waka/mailer/models/bloc/fields_create.yaml

# Update page
update:
    title: waka.mailer::bloc.update
    redirect: waka/mailer/wakamails/index/blocs
    redirectClose: waka/mailer/wakamails/index/blocs

# Preview page
preview:
    title: waka.mailer::bloc.preview_name
