# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailer::layout.form_name

# Model Form Field configuration
form: $/waka/mailer/models/layout/fields.yaml

# Model Class name
modelClass: Waka\Mailer\Models\Layout

# Default redirect location
defaultRedirect: waka/mailer/layouts

# Create page
create:
    title: waka.mailer::layout.create
    redirect: waka/mailer/layouts/update/:id
    redirectClose: waka/mailer/layouts

# Update page
update:
    title: waka.mailer::layout.update
    redirect: waka/mailer/layouts
    redirectClose: waka/mailer/layouts

# Preview page
preview:
    title: waka.mailer::layout.preview_name
